### ISSUE TITLE
Fail to read some of the *.pcap file

### ISSUE THREAD

**Issue by Guolin-Yin** [zeroby0/csi-explorer#1]
Firstly thanks for your amazing tool which is real helpful for my project.
I successfully read the received CSI value on some of my received .pcap files. 
However, some of the .pcap files fail to be explored. There are two kinds of error messages, some .pcap files gives error  message
 `Traceback (most recent call last):
  File "main.py", line 8, in <module>
    plotter  = Plotter(explorer.get_sample(0).csi)
  File "/Users/guolinyin/CSI-plot-and-Analysis/csi-explorer-main/CsiExplorer.py", line 158, in get_sample
    return self.samples[sample_index]
IndexError: list index out of range`

and some of them gives the error message:
`Traceback (most recent call last):
  File "main.py", line 7, in <module>
    explorer = Explorer(f'./files/{filename}')
  File "/Users/guolinyin/CSI-plot-and-Analysis/csi-explorer-main/CsiExplorer.py", line 12, in __init__
    self.__read()
  File "/Users/guolinyin/CSI-plot-and-Analysis/csi-explorer-main/CsiExplorer.py", line 154, in __read
    self.samples.append(self.__read_frame(pcapfile))
  File "/Users/guolinyin/CSI-plot-and-Analysis/csi-explorer-main/CsiExplorer.py", line 127, in __read_frame
    csi.set_fcsc(fc, sc)
  File "/Users/guolinyin/CSI-plot-and-Analysis/csi-explorer-main/CsiSample.py", line 36, in set_fcsc
    self.type    = PacketTypes.TypeMap[maintype]['Type']
KeyError: 14`

I'm using one Raspberry 4B to collect those CSI with specific MAC address and another pi 4 to connect to an AP and use `ping` to generate traffic to the channel. I think the possible reason for those error message is because the `ping` may not always stable. Hence, I am planning to use Nexmon frame injection or scapy to send frames for CSI capture. Have you got any advise to solve this problem? and what method do you usually use to generate traffic? @zeroby0

**Comment by zeroby0** [comment]
Hey Colin!

I'm surprised that you're using this tool, I never expected it to be used by anyone 😂. Thanks for using it 😄 

Can you post the pcap files you are using? I'll try to debug with them.

**Comment by Colin-Guolin** [comment]
Hi my friend, thank for your replying.
Since my project using deep learning method to deal with those CSI on python, and your tool is based on python, so it is perfect tool for me to use, and it saved me huge amount of time, haha. Thanks again.
I upload those error .pcap files to my GitHub [repositories,](https://github.com/Colin-Guolin/PCAP-Files-with-error) please check it, if your have time for this.
Setting up the transmitter is the one last step of my platform, I am not sure what tools should I use to generate traffic with specific packets rate and bandwidth for my receiver to capture CSI, have you got any advise?

**Comment by Guolin-Yin** [comment]
> Hey Colin!
> 
> I'm surprised that you're using this tool, I never expected it to be used by anyone 😂. Thanks for using it 😄
> 
> Can you post the pcap files you are using? I'll try to debug with them.
Hi my friend, thank for your replying.
Since my project using deep learning method to deal with those CSI on python, and your tool is based on python, so it is perfect tool for me to use, and it saved me huge amount of time, haha. Thanks again.
I upload those error .pcap files to my GitHub [repositories,](https://github.com/Colin-Guolin/PCAP-Files-with-error) please check it, if your have time for this.
Setting up the transmitter is the one last step of my platform, I am not sure what tools should I use to generate traffic with specific packets rate and bandwidth for my receiver to capture CSI, have you got any advise?

**Comment by zeroby0** [comment]
So I looked at the files, and here is why they failed to decode:

* out1.pcap, outputcsi.pcap: These files are empty with only the 24 bytes pcap header. There are no csi samples recorded in them.
* Guolin.pcap: This file looks to be created with the nexmon_csi master branch. csi-explorer is intended to be used with [pi-5.4.51-plus](https://github.com/nexmonster/nexmon_csi/tree/pi-5.4.51-plus) branch. 

I'm working on the python parser for the master branch. I'll tag you when it's available :)

**Comment by Guolin-Yin** [comment]
> So I looked at the files, and here is why they failed to decode:
> 
> * out1.pcap, outputcsi.pcap: These files are empty with only the 24 bytes pcap header. There are no csi samples recorded in them.
> * Guolin.pcap: This file looks to be created with the nexmon_csi master branch. csi-explorer is intended to be used with [pi-5.4.51-plus](https://github.com/nexmonster/nexmon_csi/tree/pi-5.4.51-plus) branch.
> 
> I'm working on the python parser for the master branch. I'll tag you when it's available :)

Morning

That make sense. It real helpful, thanks you a lot.

**Comment by Guolin-Yin** [comment]
Hi @zeroby0 
There is a tool called "[CSIKit](https://pypi.org/project/CSIKit/)" written in python with numpy, can extract CSI from the .pcap file that generate from the master branch, you might interested in, see the link below:
https://pypi.org/project/CSIKit/

**Comment by zeroby0** [comment]
The author of csikit is collaborating with us to make the next version of python reader :)

It's 98% done. I'm just adding a little bit of last touches. Should be ready in 3-4 hours.

**Comment by Guolin-Yin** [comment]
That is wonderful. Looking forward to your work. Please tag me when it ready. Thanks in advance.

**Comment by zeroby0** [comment]
It's up! :)

https://github.com/zeroby0/nexmon_csi/tree/feature/python/utils/python

**Comment by Guolin-Yin** [comment]
Thanks bro. I really appreciate you guys working.

**Comment by Guolin-Yin** [comment]
Hi @zeroby0 
I have looked into the code of your latest version of CSI [explorer](https://github.com/zeroby0/nexmon_csi/tree/feature/python/utils/python), I have noticed that a piece of code, from [line 263](https://github.com/zeroby0/nexmon_csi/blob/37665448f975aa4ed1883b73ef1debe3aa826699/utils/python/decoders/interleaved.py#L263) to [line 266](https://github.com/zeroby0/nexmon_csi/blob/37665448f975aa4ed1883b73ef1debe3aa826699/utils/python/decoders/interleaved.py#L266) of the interleaved.py, it suggests that this version of CSI explorer is intended to be used with your branch [pi-4.19.97](https://github.com/zeroby0/nexmon_csi/tree/pi-4.19.97) and [pi-5.4.51](https://github.com/zeroby0/nexmon_csi/tree/pi-5.4.51), since the code corresponding to the embedded data structure: 
![image](https://user-images.githubusercontent.com/73445515/102350609-10d8ef80-3f9d-11eb-8f6f-170c099df5e8.png)
Is my understanding right?

**Comment by zeroby0** [comment]
That's correct.

The 4.19.97 and 5.4.51 branches do not change the data structure, so it's compatible with nexmon_csi master branch as well.

The pi-x versions add only stability fixes to nexmon csi and do not change behaviour. The pi-x-plus branches add stability fixes and add new features.

**Comment by Guolin-Yin** [comment]
Thanks for your time. @zeroby0 

I run the latest version of CSI explorer and got the figure 
![image](https://user-images.githubusercontent.com/73445515/102535226-d441ec80-409f-11eb-957c-6ca579ba3cb2.png)
I have some questions can't figure out by myself:

I removed unused subcarrier, I'm not quite understand the amplitude part of this figure, it ranges from around 300 to 700, I am just wondering what is the unit of the amplitude? 

Besides, the amplitude of the subcarrier 27 and 28 (around x-axis: 0 on the figure) is significant lower than the others, do you think there are some thing wrong?

All the Sequence and fragment number, extracted by `sc, fn = samples.get_seq(index=200)`, are 0, (my .pcap file was obtained by using 4.19.97 and 5.4.51 branches), any idea for this issues? It seems fine on the Wireshark

Sorry to bother you again, thanks in advance.
